baseURL = "https://pooyan.xyz/"
languageCode = "en-us"
title = "Pooyan Goodarzi"
theme = "notrack"
pagination.pagerSize = 8  # Posts per page, e.g. in the blog

[params]
author = "Pooyan Goodarzi"
siteHeading = "Pooyan Goodarzi" # defaults to author
favicon = "favicon.png" # The small icon shown in browser tabs
showTaxonomyLinks = true  # Show e.g. a "Category" button at top of blog page

# You can choose to display a summary of your blog on the home page. Below are
# the settings relevant for that.
showBlogLatest = true  # Whether to show it or not
mainSections = ["blog"]  # Section name of your blog (folder name)
blogLatestHeading = "My Blog Posts"  # Heading above blog summary
nBlogLatest = 4  # Number of blog post in summary

[params.social]
gitlab = "example"
# linkedin = "example"
email = "pgood007@ucr.edu"
# mastodon = ""
rss = "yes"  # Value doesn't matter - it will always link to your blog RSS
# keybase = "example"

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
